spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpaBoard
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true print 로 찍어내는거, logging 으로 해야됨
        format_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
